version: "3.7"
services:
  pinot-server:
    image: apachepinot/pinot:1.1.0
    command: "StartServer -zkAddress pinot-zookeeper1:2181,pinot-zookeeper2:2181,pinot-zookeeper3:2181"
    restart: unless-stopped
    container_name: "pinot-server"
    hostname: pinot-server
    ports:
      - "8098:8098"
    environment:
      JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms4G -Xmx48G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-server.log"
    depends_on:
      - pinot-broker
