version: "3.7"
services:
  pinot-controller:
    image: apachepinot/pinot:1.1.0
    command: "StartController -zkAddress pinot-zookeeper1:2181,pinot-zookeeper2:2181,pinot-zookeeper3:2181"
    container_name: pinot-controller
    hostname: pinot-controller
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms1G -Xmx12G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-controller.log"
